/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hospital_EAN;
import static Hospital_EAN.Pacientes.conn;
import java.awt.HeadlessException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HUGO DIAZ
 */
public class CrearCita extends javax.swing.JFrame {
    static Connection conn=null;
   // static Statement st=null;
   // static ResultSet rp=null;

  
    
    /**
     * Creates new form Pacientes
     */
    public CrearCita() {
        initComponents();
        String sql="SELECT * FROM CONTADOR";
        
        int contador;
        try {
            conn=Main.Enlace(conn);
            Statement st = conn.createStatement();
            ResultSet rs;
            rs = st.executeQuery(sql);
            while (rs.next()){
              contador= rs.getInt(1);
              //JOptionPane.showMessageDialog(null,contador);
              TxtCita.setText(Integer.toString(contador));
              
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pacientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtCedula = new javax.swing.JTextField();
        TxtNombre = new javax.swing.JTextField();
        TxtFecNac = new javax.swing.JTextField();
        TxtSexo = new javax.swing.JTextField();
        BSalir1 = new javax.swing.JButton();
        BAyudaPaciente = new javax.swing.JButton();
        BGrabarCita = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        TxtServicio = new javax.swing.JTextField();
        TxtDescripcion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TxtCosto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TxtFecCit = new javax.swing.JTextField();
        BAyudaServicio = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        TxtIdMedico = new javax.swing.JTextField();
        TxtNomMedico = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TxtEspecialidad = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        BAyudaMedico = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        TxtCita = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CREAR CITA");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("CEDULA :");

        jLabel3.setText("NOMBRE :");

        jLabel4.setText("FECHA NACIMIENTO :");

        jLabel5.setText("SEXO :");

        BSalir1.setBackground(new java.awt.Color(0, 51, 153));
        BSalir1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BSalir1.setForeground(new java.awt.Color(255, 255, 255));
        BSalir1.setText("REGRESAR");
        BSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalir1ActionPerformed(evt);
            }
        });

        BAyudaPaciente.setBackground(new java.awt.Color(0, 51, 153));
        BAyudaPaciente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BAyudaPaciente.setForeground(new java.awt.Color(255, 255, 255));
        BAyudaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAyudaPacienteActionPerformed(evt);
            }
        });

        BGrabarCita.setBackground(new java.awt.Color(0, 51, 153));
        BGrabarCita.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BGrabarCita.setForeground(new java.awt.Color(255, 255, 255));
        BGrabarCita.setText("GRABAR");
        BGrabarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGrabarCitaActionPerformed(evt);
            }
        });

        jLabel7.setText("SERVICIO :");

        jLabel8.setText("DESCRIPCION :");

        jLabel9.setText("COSTO :");

        jLabel10.setText("FECHA CITA :");

        BAyudaServicio.setBackground(new java.awt.Color(0, 51, 153));
        BAyudaServicio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BAyudaServicio.setForeground(new java.awt.Color(255, 255, 255));
        BAyudaServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAyudaServicioActionPerformed(evt);
            }
        });

        jLabel11.setText("ID MEDICO :");

        jLabel12.setText("NOMBRE MEDICO :");

        jLabel13.setText("ESPECIALIDAD :");

        BAyudaMedico.setBackground(new java.awt.Color(0, 51, 153));
        BAyudaMedico.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BAyudaMedico.setForeground(new java.awt.Color(255, 255, 255));
        BAyudaMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAyudaMedicoActionPerformed(evt);
            }
        });

        jLabel6.setText("Nro Cita :");

        TxtCita.setEditable(false);
        TxtCita.setBackground(new java.awt.Color(0, 153, 255));
        TxtCita.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TxtCita.setForeground(new java.awt.Color(204, 0, 51));
        TxtCita.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(BGrabarCita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 436, Short.MAX_VALUE)
                .addComponent(BSalir1)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(TxtIdMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BAyudaMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(TxtFecCit, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(TxtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BAyudaServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(TxtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtFecNac, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtDescripcion)
                        .addComponent(TxtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtNomMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TxtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BAyudaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(233, 233, 233))
                            .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtCita, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TxtCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TxtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel2)
                                                .addComponent(TxtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(BAyudaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(TxtFecNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(TxtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel7))
                                            .addComponent(BAyudaServicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(TxtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(TxtFecCit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11))
                                    .addComponent(BAyudaMedico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(TxtIdMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtNomMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BGrabarCita)
                    .addComponent(BSalir1))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalir1ActionPerformed
        this.setVisible(false);
        Citas FCitas = new Citas();
        FCitas.setVisible(true);
        FCitas.pack();
    }//GEN-LAST:event_BSalir1ActionPerformed

    private void BAyudaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAyudaPacienteActionPerformed
        AyudaPaciente FAyudaPaciente = new AyudaPaciente();
        FAyudaPaciente.setVisible(true);
        FAyudaPaciente.pack();
        
    }//GEN-LAST:event_BAyudaPacienteActionPerformed

    private void BGrabarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGrabarCitaActionPerformed
        try{
            conn=Main.Enlace(conn);
            
            //actualizar contador conecutivo de citas
            String sqlcontador="UPDATE CONTADOR SET IDCONTADOR = IDCONTADOR + 1";
            PreparedStatement pstu=conn.prepareStatement(sqlcontador);
            String sqlinsertar="INSERT INTO CITAS VALUES(?,?,?,?,?,?)";
            PreparedStatement psta=conn.prepareStatement(sqlinsertar);
            
            psta.setInt(1, Integer.parseInt(TxtCita.getText()));  
            psta.setString(2, TxtCedula.getText());
            psta.setString(3, TxtServicio.getText());
            psta.setString(4, TxtIdMedico.getText());
            psta.setString(5, TxtFecCit.getText());
            psta.setString(6, "PENDIENTE");
           // JOptionPane.showMessageDialog(null,sqlinsertar);
            psta.execute();
            psta.close();
            pstu.executeUpdate();
            pstu.close();
            
            this.TxtCita.setText(null);
            this.TxtCedula.setText(null);
            this.TxtServicio.setText(null);
            this.TxtIdMedico.setText(null);
            this.TxtFecCit.setText(null);
            this.TxtNombre.setText(null);
            this.TxtFecNac.setText(null);
            this.TxtSexo.setText(null);
            this.TxtCosto.setText(null);
            this.TxtDescripcion.setText(null);
            this.TxtNomMedico.setText(null);
            this.TxtEspecialidad.setText(null);
            JOptionPane.showMessageDialog(null,"Cita generada");
        }catch (Exception e){
            System.out.println(e.getCause());
        }
    }//GEN-LAST:event_BGrabarCitaActionPerformed

    private void BAyudaServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAyudaServicioActionPerformed
        AyudaServicio FAyudaServicio = new AyudaServicio();
        FAyudaServicio.setVisible(true);
        FAyudaServicio.pack();
    }//GEN-LAST:event_BAyudaServicioActionPerformed

    private void BAyudaMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAyudaMedicoActionPerformed
        AyudaMedico FAyudaMedico = new AyudaMedico();
        FAyudaMedico.setVisible(true);
        FAyudaMedico.pack();
    }//GEN-LAST:event_BAyudaMedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAyudaMedico;
    private javax.swing.JButton BAyudaPaciente;
    private javax.swing.JButton BAyudaServicio;
    private javax.swing.JButton BGrabarCita;
    private javax.swing.JButton BSalir1;
    public static javax.swing.JTextField TxtCedula;
    private javax.swing.JTextField TxtCita;
    public static javax.swing.JTextField TxtCosto;
    public static javax.swing.JTextField TxtDescripcion;
    public static javax.swing.JTextField TxtEspecialidad;
    private javax.swing.JTextField TxtFecCit;
    public static javax.swing.JTextField TxtFecNac;
    public static javax.swing.JTextField TxtIdMedico;
    public static javax.swing.JTextField TxtNomMedico;
    public static javax.swing.JTextField TxtNombre;
    public static javax.swing.JTextField TxtServicio;
    public static javax.swing.JTextField TxtSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
