/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hospital_EAN;
import java.awt.HeadlessException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HUGO DIAZ
 */
public class Servicios extends javax.swing.JFrame {
    static Connection conn=null;
   // static Statement st=null;
   // static ResultSet rp=null;

  
    
    /**
     * Creates new form Pacientes
     */
    public Servicios() {
        initComponents();
        mostrarDatosPaciente("");
    }
    
    void mostrarDatosPaciente(String valor){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("CODIGO SERVICIO");
        modelo.addColumn("DESCRIPCION");
        modelo.addColumn("COSTO");
        
        TablaServicio.setModel(modelo);
        String sql="";
        if (valor.equals(""))
        {
            sql="SELECT * FROM SERVICIO";
        }
        else
        {
            sql="SELECT * FROM SERVICIO WHERE IDSERVICIO='"+valor+"'";
        }
        String datos[] = new String [3];
        try {
            conn=Main.Enlace(conn);
            Statement st = conn.createStatement();
            ResultSet rs;
            rs = st.executeQuery(sql);
            while (rs.next()){
                datos[0]= rs.getString(1);
                datos[1]= rs.getString(2);
                datos[2]= rs.getString(3);
                
                modelo.addRow(datos);
            }
            TablaServicio.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(Servicios.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        BMostrarDatos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtServicio = new javax.swing.JTextField();
        TxtDescripcion = new javax.swing.JTextField();
        TxtCosto = new javax.swing.JTextField();
        BSalir1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaServicio = new javax.swing.JTable();
        TxtBuscar = new javax.swing.JTextField();
        BGrabarServicio = new javax.swing.JButton();
        BBuscar1 = new javax.swing.JButton();
        BActualizar = new javax.swing.JButton();

        jMenuItem1.setText("Modificar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Eliminar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        BMostrarDatos.setBackground(new java.awt.Color(0, 51, 153));
        BMostrarDatos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BMostrarDatos.setForeground(new java.awt.Color(255, 255, 255));
        BMostrarDatos.setText("MOSTRAR DATOS");
        BMostrarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMostrarDatosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONSULTA DE SERVICIOS");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("CODIGO SERVICIO :");

        jLabel3.setText("DESCRIPCION :");

        jLabel4.setText("COSTO :");

        BSalir1.setBackground(new java.awt.Color(0, 51, 153));
        BSalir1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BSalir1.setForeground(new java.awt.Color(255, 255, 255));
        BSalir1.setText("REGRESAR");
        BSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalir1ActionPerformed(evt);
            }
        });

        TablaServicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaServicio.setComponentPopupMenu(jPopupMenu1);
        TablaServicio.setGridColor(new java.awt.Color(0, 128, 128));
        TablaServicio.setSelectionForeground(new java.awt.Color(0, 255, 255));
        jScrollPane1.setViewportView(TablaServicio);

        BGrabarServicio.setBackground(new java.awt.Color(0, 51, 153));
        BGrabarServicio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BGrabarServicio.setForeground(new java.awt.Color(255, 255, 255));
        BGrabarServicio.setText("GRABAR");
        BGrabarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGrabarServicioActionPerformed(evt);
            }
        });

        BBuscar1.setBackground(new java.awt.Color(0, 51, 153));
        BBuscar1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BBuscar1.setForeground(new java.awt.Color(255, 255, 255));
        BBuscar1.setText("BUSCAR");
        BBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBuscar1ActionPerformed(evt);
            }
        });

        BActualizar.setBackground(new java.awt.Color(0, 51, 153));
        BActualizar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BActualizar.setForeground(new java.awt.Color(255, 255, 255));
        BActualizar.setText("ACTUALIZAR");
        BActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(BGrabarServicio)
                            .addGap(18, 18, 18)
                            .addComponent(BActualizar))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(29, 29, 29)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TxtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(17, 17, 17)
                            .addComponent(BBuscar1)
                            .addGap(18, 18, 18)
                            .addComponent(BMostrarDatos)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(BSalir1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(TxtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BGrabarServicio)
                    .addComponent(BActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BBuscar1)
                    .addComponent(BMostrarDatos))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BSalir1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BMostrarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMostrarDatosActionPerformed
             mostrarDatosPaciente("");
    }//GEN-LAST:event_BMostrarDatosActionPerformed

    private void BSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalir1ActionPerformed
        this.setVisible(false);
        Menu FMenu = new Menu();
        FMenu.setVisible(true);
        FMenu.pack();
    }//GEN-LAST:event_BSalir1ActionPerformed

    private void BGrabarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGrabarServicioActionPerformed
         try{
            conn=Main.Enlace(conn);
            String sqlinsertar="INSERT INTO SERVICIO VALUES(?,?,?)";
            PreparedStatement psta=conn.prepareStatement(sqlinsertar);
            psta.setString(1, TxtServicio.getText());
            psta.setString(2, TxtDescripcion.getText());
            psta.setString(3, TxtCosto.getText());
            
            psta.execute();
            psta.close();
            mostrarDatosPaciente("");
            this.TxtServicio.setText(null);
            this.TxtDescripcion.setText(null);
            this.TxtCosto.setText(null);

        }catch (Exception e){
            System.out.println(e.getCause());
        }
    }//GEN-LAST:event_BGrabarServicioActionPerformed

    private void BBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBuscar1ActionPerformed
            mostrarDatosPaciente(TxtBuscar.getText());
            this.TxtBuscar.setText(null);
    }//GEN-LAST:event_BBuscar1ActionPerformed

    private void BActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActualizarActionPerformed
            try{
                conn=Main.Enlace(conn);
                String sqlupdate="UPDATE SERVICIO SET IDSERVICIO ='"+TxtServicio.getText()+"', DESCRIPCION ='"+TxtDescripcion.getText()+"', COSTO = '"+TxtCosto.getText()+"' WHERE IDSERVICIO='"+TxtServicio.getText()+"'";
               // JOptionPane.showMessageDialog(null,sqlupdate);
                PreparedStatement psta=conn.prepareStatement(sqlupdate);
                psta.executeUpdate();
                mostrarDatosPaciente("");
            }catch (Exception e){
                System.out.print(e.getMessage());
            }
                
            
    }//GEN-LAST:event_BActualizarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
            int fila=TablaServicio.getSelectedRow();
            //JOptionPane.showMessageDialog(null,fila);
            if (fila>=0)
            {
                TxtServicio.setText(TablaServicio.getValueAt(fila, 0).toString());
                TxtDescripcion.setText(TablaServicio.getValueAt(fila, 1).toString());
                TxtCosto.setText(TablaServicio.getValueAt(fila, 2).toString());
                
            }
            else
            {
                JOptionPane.showMessageDialog(null,"No selecciono fila");
            }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
            int fila=TablaServicio.getSelectedRow();
            String cedula=TablaServicio.getValueAt(fila, 0).toString();
            
            try{
                conn=Main.Enlace(conn);
                String sqldelete="DELETE FROM SERVICIO WHERE IDSERVICIO='"+cedula+"'";
                JOptionPane.showMessageDialog(null,sqldelete);
                PreparedStatement psta=conn.prepareStatement(sqldelete);
                psta.executeUpdate();
                mostrarDatosPaciente("");
            }catch (Exception e){
                System.out.print(e.getMessage());
            }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Servicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BActualizar;
    private javax.swing.JButton BBuscar1;
    private javax.swing.JButton BGrabarServicio;
    private javax.swing.JButton BMostrarDatos;
    private javax.swing.JButton BSalir1;
    private javax.swing.JTable TablaServicio;
    private javax.swing.JTextField TxtBuscar;
    private javax.swing.JTextField TxtCosto;
    private javax.swing.JTextField TxtDescripcion;
    private javax.swing.JTextField TxtServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
